### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [Insert-Creative-Name-Here/gitstatus.zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add plugins with a readme so that users can see how to use them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Insert-Creative-Name-Here** [comment]
Thanks for reminding me!

I'll get to adding these files in a minute.

**Comment by Insert-Creative-Name-Here** [comment]
Added the necessary documentation for the project. Closed issue.
